<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "jo_content"
 *
 * manually generated by JO
 *
 * Manual updates:
 * "version" and "dependencies" must not be touched!
 ***************************************************************/
$EM_CONF[$_EXTKEY] = [
    'title' => 'JO Contentelement Base',
    'description' => 'JO Contentelemente optimized for bootstrap',
    'category' => 'plugin',
    'state' => 'stable',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 1,
    'lockType' => '',
    'author' => 'TYPO3 Team JUSTORANGE',
	'author_email' => 'info@justorange.de',
    'author_company' => 'JUSTORANGE',
    'version' => '11.5.23',
    'constraints' => [
        'depends' => [
            'news' => '9.4.0-11.9.99',
        ],
        'conflicts' => [],
        'suggests' => []
    ],
    'autoload' => [
        'psr-4' => [
            'JO\\JoContent\\' => 'Classes'
        ]
    ]
];
